/*************************************************************************/
/*  lua_prelude.cpp                                                      */
/*************************************************************************/
/*  Lua implementations of Godot 4 math methods that Godot 2 lacks, or   */
/*  whose Godot 2 semantics differ (reflect/bounce treat self as the     */
/*  normal in Godot 2). Explicit methods take precedence over the        */
/*  Variant-reflection fallback, so these override the engine versions.  */
/*************************************************************************/

#include "lua_bridge.h"

namespace sunaba {

static const char *PRELUDE =
		"local V2, V3, R2, AB, C = Vector2, Vector3, Rect2, AABB, Color\n"
		"local abs, floor, ceil, min, max, fmod = math.abs, math.floor, math.ceil, math.min, math.max, math.fmod\n"
		"local EPS = 0.00001\n"
		"local function approx(a, b)\n"
		"  if a == b then return true end\n"
		"  local tol = EPS * abs(a)\n"
		"  if tol < EPS then tol = EPS end\n"
		"  return abs(a - b) < tol\n"
		"end\n"
		"local function sgn(x) if x > 0 then return 1 elseif x < 0 then return -1 end return 0 end\n"
		"local function rnd(x) if x >= 0 then return floor(x + 0.5) end return ceil(x - 0.5) end\n"
		"local function pmod(a, b)\n"
		"  local v = fmod(a, b)\n"
		"  if (v < 0 and b > 0) or (v > 0 and b < 0) then v = v + b end\n"
		"  return v\n"
		"end\n"
		"local function clampf(x, a, b) if x < a then return a elseif x > b then return b end return x end\n"
		"\n"
		"-- Shared vector helpers (work for Vector2 and Vector3).\n"
		"local function vec_methods(T, comps)\n"
		"  local function map(v, f)\n"
		"    local r = {}\n"
		"    for i, c in ipairs(comps) do r[i] = f(v[c]) end\n"
		"    return T.new(table.unpack(r))\n"
		"  end\n"
		"  local function map2(a, b, f)\n"
		"    local r = {}\n"
		"    for i, c in ipairs(comps) do r[i] = f(a[c], b[c]) end\n"
		"    return T.new(table.unpack(r))\n"
		"  end\n"
		"  function T.isNormalized(v) return approx(v:lengthSquared(), 1) end\n"
		"  function T.normalize(v)\n"
		"    local n = v:normalized()\n"
		"    for _, c in ipairs(comps) do v[c] = n[c] end\n"
		"  end\n"
		"  function T.min(a, b) return map2(a, b, min) end\n"
		"  function T.max(a, b) return map2(a, b, max) end\n"
		"  function T.sign(v) return map(v, sgn) end\n"
		"  function T.round(v) return map(v, rnd) end\n"
		"  function T.ceil(v) return map(v, ceil) end\n"
		"  function T.floor(v) return map(v, floor) end\n"
		"  function T.abs(v) return map(v, abs) end\n"
		"  function T.posmod(v, m) return map(v, function(x) return pmod(x, m) end) end\n"
		"  function T.posmodv(v, m) return map2(v, m, pmod) end\n"
		"  function T.clamp(v, lo, hi)\n"
		"    local r = {}\n"
		"    for i, c in ipairs(comps) do r[i] = clampf(v[c], lo[c], hi[c]) end\n"
		"    return T.new(table.unpack(r))\n"
		"  end\n"
		"  function T.isEqualApprox(a, b)\n"
		"    for _, c in ipairs(comps) do if not approx(a[c], b[c]) then return false end end\n"
		"    return true\n"
		"  end\n"
		"  function T.isZeroApprox(v)\n"
		"    for _, c in ipairs(comps) do if abs(v[c]) >= EPS then return false end end\n"
		"    return true\n"
		"  end\n"
		"  function T.directionTo(a, b) return (b - a):normalized() end\n"
		"  function T.limitLength(v, len)\n"
		"    len = len or 1.0\n"
		"    local l = v:length()\n"
		"    if l > 0 and len < l then return v / l * len end\n"
		"    return v\n"
		"  end\n"
		"  function T.moveToward(v, to, delta)\n"
		"    local vd = to - v\n"
		"    local len = vd:length()\n"
		"    if len <= delta or len < EPS then return to end\n"
		"    return v + vd / len * delta\n"
		"  end\n"
		"  function T.project(v, b) return b * (v:dot(b) / b:lengthSquared()) end\n"
		"  function T.slide(v, n) return v - n * v:dot(n) end\n"
		"  function T.reflect(v, n) return n * (2.0 * v:dot(n)) - v end\n"
		"  function T.bounce(v, n) return -T.reflect(v, n) end\n"
		"end\n"
		"vec_methods(V2, { 'x', 'y' })\n"
		"vec_methods(V3, { 'x', 'y', 'z' })\n"
		"\n"
		"-- Rect2 / AABB\n"
		"function R2.getCenter(r) return r.position + r.size / 2 end\n"
		"function R2.hasArea(r) return r.size.x > 0 and r.size.y > 0 end\n"
		"function R2.abs(r)\n"
		"  return R2.new(r.position + r.size:min(V2.new(0, 0)), r.size:abs())\n"
		"end\n"
		"function R2.isEqualApprox(a, b)\n"
		"  return a.position:isEqualApprox(b.position) and a.size:isEqualApprox(b.size)\n"
		"end\n"
		"function AB.getCenter(b) return b.position + b.size / 2 end\n"
		"function AB.hasVolume(b) return b.size.x > 0 and b.size.y > 0 and b.size.z > 0 end\n"
		"function AB.hasSurface(b) return b.size.x > 0 or b.size.y > 0 or b.size.z > 0 end\n"
		"function AB.abs(b)\n"
		"  return AB.new(b.position + b.size:min(V3.new(0, 0, 0)), b.size:abs())\n"
		"end\n"
		"\n"
		"-- Color\n"
		"local color_new = C.new\n"
		"function C.new(a, ...)\n"
		"  -- Godot 4 Color(from, alpha)\n"
		"  if type(a) == 'userdata' and select('#', ...) == 1 and type((...)) == 'number' then\n"
		"    return color_new(a.r, a.g, a.b, (...))\n"
		"  end\n"
		"  return color_new(a, ...)\n"
		"end\n"
		"function C.lightened(c, amount)\n"
		"  return color_new(c.r + (1 - c.r) * amount, c.g + (1 - c.g) * amount, c.b + (1 - c.b) * amount, c.a)\n"
		"end\n"
		"function C.darkened(c, amount)\n"
		"  return color_new(c.r * (1 - amount), c.g * (1 - amount), c.b * (1 - amount), c.a)\n"
		"end\n"
		"function C.getLuminance(c) return 0.2126 * c.r + 0.7152 * c.g + 0.0722 * c.b end\n"
		"function C.clamp(c, lo, hi)\n"
		"  lo = lo or color_new(0, 0, 0, 0)\n"
		"  hi = hi or color_new(1, 1, 1, 1)\n"
		"  return color_new(clampf(c.r, lo.r, hi.r), clampf(c.g, lo.g, hi.g), clampf(c.b, lo.b, hi.b), clampf(c.a, lo.a, hi.a))\n"
		"end\n"
		"function C.isEqualApprox(a, b)\n"
		"  return approx(a.r, b.r) and approx(a.g, b.g) and approx(a.b, b.b) and approx(a.a, b.a)\n"
		"end\n";

void run_prelude(lua_State *L) {

	if (luaL_loadbuffer(L, PRELUDE, strlen(PRELUDE), "=sunaba_prelude") != LUA_OK || pcall_traceback(L, 0, 0) != LUA_OK)
		report_error(L, "Prelude");
}

} // namespace sunaba
